version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line
      # - /srv/app/var
      # If you develop on Windows you can greatly improve performance by using Docker
      # volumes for the vendor and var directories by enabling the next 2 lines and 
      # the "volumes" block at the bottom of this file
      # - vendor:/srv/app/vendor
      # - var:/srv/app/var
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

# You can uncomment this to improve performance on Windows (see above)
# volumes:
#   vendor:
#   var:
